package com.jawahar.secure.core;

import android.content.Context;
import org.json.JSONObject;
import org.webrtc.*;
import java.io.*;import java.nio.ByteBuffer;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;

/** Direct encrypted file transport. The file sent here is already a Jawahar AES-GCM container. */
public final class DirectRtc {
 private DirectRtc(){} private static final Object LOCK=new Object();private static volatile boolean init;private static final int CHUNK=48*1024;private static final long MAX_BUFFERED=3L*1024*1024;
 public interface Listener{default void onState(String s){}default void onProgress(long done,long total){}default void onComplete(){}default void onFailed(Throwable e){}}
 private static void initialize(Context c){if(init)return;synchronized(LOCK){if(init)return;PeerConnectionFactory.initialize(PeerConnectionFactory.InitializationOptions.builder(c.getApplicationContext()).setEnableInternalTracer(false).createInitializationOptions());init=true;}}
 private static PeerConnectionFactory factory(Context c){initialize(c);return PeerConnectionFactory.builder().createPeerConnectionFactory();}
 private static PeerConnection.RTCConfiguration config(){List<PeerConnection.IceServer> ice=Arrays.asList(PeerConnection.IceServer.builder("stun:stun.l.google.com:19302").createIceServer(),PeerConnection.IceServer.builder("stun:stun1.l.google.com:19302").createIceServer());PeerConnection.RTCConfiguration r=new PeerConnection.RTCConfiguration(ice);r.sdpSemantics=PeerConnection.SdpSemantics.UNIFIED_PLAN;r.continualGatheringPolicy=PeerConnection.ContinualGatheringPolicy.GATHER_ONCE;r.iceCandidatePoolSize=2;r.tcpCandidatePolicy=PeerConnection.TcpCandidatePolicy.ENABLED;r.keyType=PeerConnection.KeyType.ECDSA;return r;}
 private static abstract class Obs implements PeerConnection.Observer{final CountDownLatch iceDone=new CountDownLatch(1);final Listener l;Obs(Listener x){l=x;}public void onSignalingChange(PeerConnection.SignalingState s){}public void onIceConnectionChange(PeerConnection.IceConnectionState s){if(s==PeerConnection.IceConnectionState.CONNECTED||s==PeerConnection.IceConnectionState.COMPLETED)l.onState("connected");else if(s==PeerConnection.IceConnectionState.CHECKING)l.onState("connecting");else if(s==PeerConnection.IceConnectionState.FAILED)l.onFailed(new IOException("Direct connection failed"));}public void onConnectionChange(PeerConnection.PeerConnectionState s){if(s==PeerConnection.PeerConnectionState.CONNECTED)l.onState("connected");else if(s==PeerConnection.PeerConnectionState.CONNECTING)l.onState("connecting");else if(s==PeerConnection.PeerConnectionState.FAILED)l.onFailed(new IOException("Direct connection failed"));}public void onIceConnectionReceivingChange(boolean b){}public void onIceGatheringChange(PeerConnection.IceGatheringState s){if(s==PeerConnection.IceGatheringState.COMPLETE)iceDone.countDown();}public void onIceCandidate(IceCandidate c){}public void onIceCandidatesRemoved(IceCandidate[] c){}public void onAddStream(MediaStream s){}public void onRemoveStream(MediaStream s){}public void onDataChannel(DataChannel d){}public void onRenegotiationNeeded(){}public void onAddTrack(RtpReceiver r,MediaStream[] s){} }
 private static final class Await implements SdpObserver{final CountDownLatch l=new CountDownLatch(1);volatile SessionDescription s;volatile String e;public void onCreateSuccess(SessionDescription x){s=x;l.countDown();}public void onSetSuccess(){l.countDown();}public void onCreateFailure(String x){e=x;l.countDown();}public void onSetFailure(String x){e=x;l.countDown();}void waitFor(String what)throws Exception{if(!l.await(12,TimeUnit.SECONDS))throw new IOException(what+" timed out");if(e!=null)throw new IOException(what+": "+e);}}

 /** Friend-side receiver/answerer. */
 public static final class Receiver implements AutoCloseable{
  private final PeerConnectionFactory f;private final PeerConnection pc;private final Listener l;private final File target,part;private final Obs obs;private final AtomicReference<DataChannel> dc=new AtomicReference<>();private final AtomicBoolean complete=new AtomicBoolean(),closed=new AtomicBoolean(),answerCreated=new AtomicBoolean();private OutputStream out;private MessageDigest digest;private volatile long total=-1,received;
  public Receiver(Context c,File target,Listener l)throws Exception{this.l=l==null?new Listener(){}:l;this.target=target;this.part=new File(target.getAbsolutePath()+".part");File parent=target.getParentFile();if(parent!=null)parent.mkdirs();if(part.exists())part.delete();f=factory(c);obs=new Obs(this.l){@Override public void onDataChannel(DataChannel d){bind(d);}};pc=f.createPeerConnection(config(),obs);if(pc==null)throw new IOException("Could not create direct receiver");}
  private void bind(DataChannel d){if(!dc.compareAndSet(null,d))return;d.registerObserver(new DataChannel.Observer(){public void onBufferedAmountChange(long p){}public void onStateChange(){if(d.state()==DataChannel.State.OPEN)l.onState("connected");}public void onMessage(DataChannel.Buffer b){try{byte[]x=new byte[b.data.remaining()];b.data.get(x);if(b.binary)binary(x);else control(new String(x,StandardCharsets.UTF_8));}catch(Throwable e){l.onFailed(e);}}});}
  public String acceptOffer(String offer)throws Exception{if(!answerCreated.compareAndSet(false,true))throw new IOException("Direct answer already created");l.onState("creating_answer");Await a=new Await();pc.setRemoteDescription(a,new SessionDescription(SessionDescription.Type.OFFER,offer));a.waitFor("Apply offer");Await c=new Await();pc.createAnswer(c,new MediaConstraints());c.waitFor("Create answer");Await s=new Await();pc.setLocalDescription(s,c.s);s.waitFor("Set answer");obs.iceDone.await(8,TimeUnit.SECONDS);SessionDescription x=pc.getLocalDescription();if(x==null||x.description==null||x.description.isBlank())throw new IOException("Direct answer is empty");l.onState("connecting");return x.description;}
  private synchronized void control(String s)throws Exception{JSONObject j=new JSONObject(s);String t=j.optString("t");if("begin".equals(t)){total=j.getLong("n");received=0;if(out!=null)try{out.close();}catch(Exception ignored){}out=new BufferedOutputStream(new FileOutputStream(part),512*1024);digest=MessageDigest.getInstance("SHA-256");l.onState("transferring");}else if("end".equals(t)){if(out==null||digest==null)throw new IOException("Transfer header missing");out.flush();out.close();out=null;String got=hex(digest.digest());if(received!=total||!got.equalsIgnoreCase(j.getString("sha256"))){part.delete();throw new IOException("Direct transfer integrity check failed");}if(target.exists()&&!target.delete())throw new IOException("Could not replace previous file");if(!part.renameTo(target)){try(InputStream in=new FileInputStream(part);OutputStream o=new FileOutputStream(target)){in.transferTo(o);}part.delete();}complete.set(true);l.onProgress(received,total);l.onComplete();}}
  private synchronized void binary(byte[]b)throws Exception{if(out==null||digest==null)throw new IOException("Direct data arrived too early");out.write(b);digest.update(b);received+=b.length;l.onProgress(received,total);}
  public boolean isComplete(){return complete.get();}public boolean hasAnswerCreated(){return answerCreated.get();}
  public void close(){if(!closed.compareAndSet(false,true))return;try{if(out!=null)out.close();}catch(Exception ignored){}DataChannel d=dc.get();if(d!=null){try{d.close();}catch(Exception ignored){}try{d.dispose();}catch(Exception ignored){}}try{pc.close();}catch(Exception ignored){}try{pc.dispose();}catch(Exception ignored){}try{f.dispose();}catch(Exception ignored){}}
 }

 /** Owner-side sender/offerer. */
 public static final class Sender implements AutoCloseable{
  private final PeerConnectionFactory f;private final PeerConnection pc;private final File source;private final Listener l;private final Obs obs;private final DataChannel dc;private final AtomicBoolean started=new AtomicBoolean(),connected=new AtomicBoolean(),complete=new AtomicBoolean(),closed=new AtomicBoolean(),answerApplied=new AtomicBoolean();
  public Sender(Context c,File source,Listener l)throws Exception{this.source=source;this.l=l==null?new Listener(){}:l;f=factory(c);obs=new Obs(this.l){@Override public void onConnectionChange(PeerConnection.PeerConnectionState s){super.onConnectionChange(s);if(s==PeerConnection.PeerConnectionState.CONNECTED)connected.set(true);}@Override public void onIceConnectionChange(PeerConnection.IceConnectionState s){super.onIceConnectionChange(s);if(s==PeerConnection.IceConnectionState.CONNECTED||s==PeerConnection.IceConnectionState.COMPLETED)connected.set(true);}};pc=f.createPeerConnection(config(),obs);if(pc==null)throw new IOException("Could not create direct sender");DataChannel.Init di=new DataChannel.Init();di.ordered=true;dc=pc.createDataChannel("jawahar-file",di);if(dc==null)throw new IOException("Could not create direct data channel");dc.registerObserver(new DataChannel.Observer(){public void onBufferedAmountChange(long p){}public void onMessage(DataChannel.Buffer b){}public void onStateChange(){if(dc.state()==DataChannel.State.OPEN){connected.set(true);Sender.this.l.onState("connected");startSend();}}});}
  public String createOffer()throws Exception{l.onState("creating_offer");Await c=new Await();pc.createOffer(c,new MediaConstraints());c.waitFor("Create offer");Await s=new Await();pc.setLocalDescription(s,c.s);s.waitFor("Set offer");obs.iceDone.await(8,TimeUnit.SECONDS);SessionDescription x=pc.getLocalDescription();if(x==null||x.description==null||x.description.isBlank())throw new IOException("Direct offer is empty");return x.description;}
  public void applyAnswer(String answer)throws Exception{if(!answerApplied.compareAndSet(false,true))return;Await a=new Await();pc.setRemoteDescription(a,new SessionDescription(SessionDescription.Type.ANSWER,answer));a.waitFor("Apply answer");l.onState("connecting");}
  public boolean isConnected(){return connected.get();}public boolean isComplete(){return complete.get();}public boolean hasAnswer(){return answerApplied.get();}
  private void startSend(){if(!started.compareAndSet(false,true))return;new Thread(()->{try{send();}catch(Throwable e){l.onFailed(e);}},"jawahar-direct-send").start();}
  private void send()throws Exception{if(!source.isFile())throw new FileNotFoundException("Secure file is missing on owner phone");long total=source.length(),done=0;text(new JSONObject().put("t","begin").put("n",total).toString());MessageDigest md=MessageDigest.getInstance("SHA-256");l.onState("transferring");try(InputStream in=new BufferedInputStream(new FileInputStream(source),512*1024)){byte[]buf=new byte[CHUNK];for(int n;(n=in.read(buf))>0;){while(dc.bufferedAmount()>MAX_BUFFERED){if(dc.state()!=DataChannel.State.OPEN)throw new IOException("Direct connection closed");Thread.sleep(8);}byte[]piece=Arrays.copyOf(buf,n);md.update(piece);if(!dc.send(new DataChannel.Buffer(ByteBuffer.wrap(piece),true)))throw new IOException("Direct send failed");done+=n;l.onProgress(done,total);}}while(dc.bufferedAmount()>128*1024){if(dc.state()!=DataChannel.State.OPEN)throw new IOException("Direct connection closed");Thread.sleep(8);}text(new JSONObject().put("t","end").put("sha256",hex(md.digest())).toString());complete.set(true);l.onComplete();}
  private void text(String s)throws Exception{if(!dc.send(new DataChannel.Buffer(ByteBuffer.wrap(s.getBytes(StandardCharsets.UTF_8)),false)))throw new IOException("Direct control send failed");}
  public void close(){if(!closed.compareAndSet(false,true))return;try{dc.close();}catch(Exception ignored){}try{dc.dispose();}catch(Exception ignored){}try{pc.close();}catch(Exception ignored){}try{pc.dispose();}catch(Exception ignored){}try{f.dispose();}catch(Exception ignored){}}
 }
 private static String hex(byte[]b){StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format(Locale.US,"%02x",x));return s.toString();}
}
