package com.jawahar.secure.owner;
import com.jawahar.secure.core.*;import org.json.*;import java.io.*;import java.util.*;import java.util.concurrent.*;
public final class OwnerApi{
 private final String base,token;public OwnerApi(String b,String t){base=ApiConfig.normalize(b);token=t;if(base.isBlank()||base.contains("REPLACE-ME"))throw new IllegalArgumentException("Jawahar server is not configured in this build");}
 private Map<String,String> auth(){return Map.of("Authorization","Bearer "+token);}
 public void registerDirect(OwnerStore.FileRow f,String ownerPub)throws Exception{startUpload(f,ownerPub);}
 public void p2pOffer(String requestId,String sdp)throws Exception{JSONObject j=new JSONObject().put("sdp",sdp);var r=JsonHttp.json("POST",base+"/v1/owner/p2p/"+java.net.URLEncoder.encode(requestId,java.nio.charset.StandardCharsets.UTF_8)+"/offer",auth(),j);if(r.code/100!=2)throw new IOException(r.text());}
 public String p2pAnswer(String requestId)throws Exception{var r=JsonHttp.request("GET",base+"/v1/owner/p2p/"+java.net.URLEncoder.encode(requestId,java.nio.charset.StandardCharsets.UTF_8)+"/answer",auth(),null);if(r.code/100!=2)throw new IOException(r.text());return r.json().optString("sdp","");}
 public JSONObject startUpload(OwnerStore.FileRow f,String ownerPub)throws Exception{JSONObject j=new JSONObject().put("fileId",f.id()).put("name",f.name()).put("mime",f.mime()).put("plainSize",f.size()).put("encryptedSize",new File(f.path()).length()).put("ownerAgreePub",ownerPub);var r=JsonHttp.json("POST",base+"/v1/owner/uploads/start",auth(),j);if(r.code/100!=2)throw new IOException(r.text());return r.json();}
 public void uploadAll(OwnerStore.FileRow f,String ownerPub)throws Exception{JSONObject s=startUpload(f,ownerPub);String uploadId=s.getString("uploadId"),objectKey=s.getString("objectKey");File src=new File(f.path());final int chunk=8*1024*1024,partsCount=(int)((src.length()+chunk-1)/chunk);ExecutorService pool=Executors.newFixedThreadPool(Math.min(4,Math.max(1,partsCount)));List<Future<JSONObject>> jobs=new ArrayList<>();for(int part=1;part<=partsCount;part++){final int pn=part;jobs.add(pool.submit(()->{long off=(long)(pn-1)*chunk;int len=(int)Math.min(chunk,src.length()-off);byte[]piece=new byte[len];try(RandomAccessFile raf=new RandomAccessFile(src,"r")){raf.seek(off);raf.readFully(piece);}var r=JsonHttp.request("PUT",base+"/v1/owner/uploads/"+uploadId+"/part/"+pn+"?key="+java.net.URLEncoder.encode(objectKey,java.nio.charset.StandardCharsets.UTF_8),auth(),piece);if(r.code/100!=2)throw new IOException(r.text());JSONObject p=r.json();return new JSONObject().put("partNumber",pn).put("etag",p.getString("etag"));}));}JSONArray parts=new JSONArray();try{for(Future<JSONObject> j:jobs)parts.put(j.get());}catch(ExecutionException e){for(Future<?> j:jobs)j.cancel(true);Throwable c=e.getCause();if(c instanceof Exception ex)throw ex;throw new IOException(c);}finally{pool.shutdownNow();}JSONObject done=new JSONObject().put("fileId",f.id()).put("objectKey",objectKey).put("parts",parts);var rr=JsonHttp.json("POST",base+"/v1/owner/uploads/"+uploadId+"/complete",auth(),done);if(rr.code/100!=2)throw new IOException(rr.text());}

 public JSONArray grants()throws Exception{var r=JsonHttp.request("GET",base+"/v1/owner/grants",auth(),null);if(r.code/100!=2)throw new IOException(r.text());return r.json().getJSONArray("grants");}
 public JSONArray activity()throws Exception{var r=JsonHttp.request("GET",base+"/v1/owner/activity",auth(),null);if(r.code/100!=2)throw new IOException(r.text());return r.json().getJSONArray("rows");}
 public JSONArray activityDetails(String grantId)throws Exception{var r=JsonHttp.request("GET",base+"/v1/owner/activity/"+java.net.URLEncoder.encode(grantId,java.nio.charset.StandardCharsets.UTF_8),auth(),null);if(r.code/100!=2)throw new IOException(r.text());return r.json().getJSONArray("events");}
 public void revoke(String grantId)throws Exception{var r=JsonHttp.json("POST",base+"/v1/owner/grants/"+grantId+"/revoke",auth(),new JSONObject());if(r.code/100!=2)throw new IOException(r.text());}
 public JSONArray activitySummary()throws Exception{var r=JsonHttp.request("GET",base+"/v1/owner/activity/summary",auth(),null);if(r.code/100!=2)throw new IOException(r.text());return r.json().getJSONArray("devices");}
 public JSONArray activity(String deviceId)throws Exception{String u=base+"/v1/owner/activity?deviceId="+java.net.URLEncoder.encode(deviceId,java.nio.charset.StandardCharsets.UTF_8);var r=JsonHttp.request("GET",u,auth(),null);if(r.code/100!=2)throw new IOException(r.text());return r.json().getJSONArray("events");}
 public JSONArray pending()throws Exception{var r=JsonHttp.request("GET",base+"/v1/owner/requests",auth(),null);if(r.code/100!=2)throw new IOException(r.text());return r.json().getJSONArray("requests");}
 public void approve(String requestId,String wrapped,String iv)throws Exception{JSONObject j=new JSONObject().put("wrappedKey",wrapped).put("wrapIv",iv);var r=JsonHttp.json("POST",base+"/v1/owner/requests/"+requestId+"/approve",auth(),j);if(r.code/100!=2)throw new IOException(r.text());}
 public void reject(String requestId)throws Exception{var r=JsonHttp.json("POST",base+"/v1/owner/requests/"+requestId+"/reject",auth(),new JSONObject());if(r.code/100!=2)throw new IOException(r.text());}
}
